export const coats = [
  {
    id: "1",
    image: { fields: { file: { url: "../images/product-1.jpg" } } },
    title: "Classic Coat",
    price: 70,
    description:
      "Quilted, technical 2-layer shell jacket developed for skiing. Skiing Master is made of windproof, waterproof and breathable material in soft and comfortable quality. The material is a synthetic padding material that retains its insulating properties even when it gets damp. High collar and helmet-fitted hood provide perfect protection against wind and snow. The jacket is designed to provide maximum freedom of movement and is suitable for moderate to high activity levels in harsh weather conditions.",
    shipping: "Free shipping",
    material: "80% polyester, 20% nylon",
    designedFor: "Allround",
    size: ["xs", "s", "m", "l", "xl"],
    color: "yellow",
  },
  {
    id: "2",
    image: { fields: { file: { url: "../images/product-2.jpg" } } },
    title: "Windproof Jacket",
    price: 75,
    description:
      "Quilted, technical 2-layer shell jacket developed for skiing. Skiing Master is made of windproof, waterproof and breathable material in soft and comfortable quality. The material is a synthetic padding material that retains its insulating properties even when it gets damp. High collar and helmet-fitted hood provide perfect protection against wind and snow. The jacket is designed to provide maximum freedom of movement and is suitable for moderate to high activity levels in harsh weather conditions.",
    shipping: "Free shipping",
    material: "80% polyester, 20% nylon",
    designedFor: "Allround",
    size: ["xs", "s", "m", "l", "xl"],
    color: "teal blue",
  },
  {
    id: "3",
    image: { fields: { file: { url: "../images/product-3.jpg" } } },
    title: "Technical Jacket",
    price: 83,
    description:
      "Quilted, technical 2-layer shell jacket developed for skiing. Skiing Master is made of windproof, waterproof and breathable material in soft and comfortable quality. The material is a synthetic padding material that retains its insulating properties even when it gets damp. High collar and helmet-fitted hood provide perfect protection against wind and snow. The jacket is designed to provide maximum freedom of movement and is suitable for moderate to high activity levels in harsh weather conditions.",
    shipping: "Free shipping",
    material: "80% polyester, 20% nylon",
    designedFor: "Allround",
    size: ["xs", "s", "m", "l", "xl"],
    color: "blue, orange",
  },
  {
    id: "4",
    image: { fields: { file: { url: "../images/product-4.jpg" } } },
    title: "Camper",
    price: 65,
    description:
      "Quilted, technical 2-layer shell jacket developed for skiing. Skiing Master is made of windproof, waterproof and breathable material in soft and comfortable quality. The material is a synthetic padding material that retains its insulating properties even when it gets damp. High collar and helmet-fitted hood provide perfect protection against wind and snow. The jacket is designed to provide maximum freedom of movement and is suitable for moderate to high activity levels in harsh weather conditions.",
    shipping: "Free shipping",
    material: "80% polyester, 20% nylon",
    designedFor: "Allround",
    size: ["xs", "s", "m", "l", "xl"],
    color: "dark green",
  },
  {
    id: "5",
    image: { fields: { file: { url: "../images/product-5.jpg" } } },
    title: "Everyday Coat",
    price: 65,
    description:
      "Quilted, technical 2-layer shell jacket developed for skiing. Skiing Master is made of windproof, waterproof and breathable material in soft and comfortable quality. The material is a synthetic padding material that retains its insulating properties even when it gets damp. High collar and helmet-fitted hood provide perfect protection against wind and snow. The jacket is designed to provide maximum freedom of movement and is suitable for moderate to high activity levels in harsh weather conditions.",
    shipping: "Free shipping",
    material: "80% polyester, 20% nylon",
    designedFor: "Allround",
    size: ["xs", "s", "m", "l", "xl"],
    color: "black",
  },
  {
    id: "6",
    image: { fields: { file: { url: "../images/product-6.jpg" } } },
    title: "Comfy Skiing",
    price: 65,
    description:
      "The box-shaped fit and innovative material combination make the Comfy Skiing Jacket a perfect blend of warmth and weather protection! The secret lies in the hood, shoulder area and sleeves where selected areas are quilted with good quality materials. These technical materials in combination with the outer material, means that the jacket retains its insulating ability even in humid weather. Comfy Skiing Jacket is technical and durable which allow you to enjoy nature all year round in all kinds of weather. The jacket is designed to give you the best possible protection without compromising on comfort.",
    shipping: "Free shipping",
    material: "80% polyester, 20% nylon",
    designedFor: "Skiing, cold weather",
    size: ["xs", "s", "m", "l", "xl"],
    color: "blue, white",
  },
  {
    id: "7",
    image: { fields: { file: { url: "../images/product-7.jpg" } } },
    title: "Waterproof Jacket",
    price: 65,
    description:
      "Quilted, technical 2-layer shell jacket developed for skiing. Skiing Master is made of windproof, waterproof and breathable material in soft and comfortable quality. The material is a synthetic padding material that retains its insulating properties even when it gets damp. High collar and helmet-fitted hood provide perfect protection against wind and snow. The jacket is designed to provide maximum freedom of movement and is suitable for moderate to high activity levels in harsh weather conditions.",
    shipping: "Free shipping",
    material: "80% polyester, 20% nylon",
    designedFor: "Allround",
    size: ["xs", "s", "m", "l", "xl"],
    color: "red",
  },
  {
    id: "8",
    image: { fields: { file: { url: "../images/product-8.jpg" } } },
    title: "Skiing Jacket Pro",
    price: 65,
    description:
      "Quilted, technical 2-layer shell jacket developed for skiing. Skiing Master is made of windproof, waterproof and breathable material in soft and comfortable quality. The material is a synthetic padding material that retains its insulating properties even when it gets damp. High collar and helmet-fitted hood provide perfect protection against wind and snow. The jacket is designed to provide maximum freedom of movement and is suitable for moderate to high activity levels in harsh weather conditions.",
    shipping: "Free shipping",
    material: "80% polyester, 20% nylon",
    designedFor: "Skiing, cold weather",
    size: ["xs", "s", "m", "l", "xl"],
    color: "multicolor",
  },
];

console.log(coats);
